### ISSUE TITLE
sbt-updates is not compatible with scala 2.11.x?

### ISSUE THREAD

**Issue by jpzk** [rtimush/sbt-updates#50] opened 2015-07-07 10:31 UTC
Hi guys,

I tried to use sbt-updates with Scala 2.11.x? It couldnt resolve the dependency, so I assumed it is not in the repository, for that Scala version. I checked manually, and there is no built for these versions. Is 2.11.X support planned?

Kind regards,
jpzk

**Comment by wookietreiber** [comment] 2015-07-07 10:39
Might be related to / duplicate of #49.

**Comment by rtimush** [comment] 2015-07-07 10:49
Try 0.1.8 for now

**Comment by jpzk** [comment] 2015-07-07 12:24
It works, thank you :)

**Closed** 2015-07-07 12:37 UTC
Labels: duplicate
