### ISSUE TITLE
Plugin doesn't see updates with sbt 0.13.7

### ISSUE THREAD

**Issue by Sciss** [rtimush/sbt-updates#37] opened 2014-12-05 23:40 UTC
I'm looking at my project [Mellite](https://github.com/Sciss/Mellite/tree/b7a6669017b5ac35321bfd482545bf9b70c1c62d). If I change the `project/build.properties`sbt version from 0.13.6 to 0.13.7, and I run `sbt dependencyUpdates`, the result is that there are no updates

```
[info] Loading global plugins from /home/hhrutz/.sbt/0.13/plugins
[info] Loading project definition from /home/hhrutz/Documents/devel/Mellite/project
[info] Set current project to Mellite (in build file:/home/hhrutz/Documents/devel/Mellite/)
[info] No dependency updates found for mellite
[info] No dependency updates found for mellite-views
[info] No dependency updates found for mellite-core
[success] Total time: 4 s, completed Dec 6, 2014 12:36:13 AM
```

With sbt 0.13.6, I correctly see

```
[info] Found 1 dependency update for mellite-views
[info]   de.sciss:scalacolliderswing-interpreter : 1.20.2 -> 1.21.0
[info] Found 1 dependency update for mellite-core
[info]   de.sciss:soundprocesses : 2.9.0 -> 2.10.0
```

I don't know if this is an issue of sbt or the sbt-updates plugin. Given that sbt 0.13.7 claims to have improved caching, my guess it's sbt's fault, but perhaps it's worth checking it out.

**Comment by Sciss** [comment] 2015-04-29 20:19
Any news on this? I'm still seeing that updates are missed which makes it not a reliable tool when trying to synchronise a bunch of projects :-(

**Comment by rtimush** [comment] 2015-05-08 06:45
I still cannot reproduce the problem. SBT doesn't do any caching itself, and the plugin does neither. There may be some caching on maven central, or on your internet proxy (do you have one)?

**Comment by Sciss** [comment] 2015-05-08 12:38
I have experienced this with at least three completely unrelated ISPs, even from different countries, so the Internet connection definitely doesn't have anything to do with it. I run Debian 8, that also shouldn't matter. Have you tested with multi project builds, perhaps the plugin doesn't work correctly in this case?

**Comment by rtimush** [comment] 2015-05-08 12:46
I use it quite often on the build with ~100 subprojects, so the problem is in something different. I will try to investigate deeper, but it's hard without a way to reproduce.

**Comment by Sciss** [comment] 2015-05-08 12:47
__Another idea__: Could it have to do with locally published artifacts? Because I have encountered this problem with my own libraries which always exist both on Maven and locally via `publish-local`?

**Comment by rtimush** [comment] 2015-05-08 12:49
It won't detect new versions from the local repo, but should still report versions from maven central (unless you don't have maven central in the `resolvers` setting, of course).

**Comment by Sciss** [comment] 2015-05-08 13:41
I don't have Maven Central in the resolvers explicitly, but sbt always checks Maven Central. But my local publishes are exactly the same, i.e. they _do_ have the same latest versions as well. So no clue.

**Comment by rtimush** [comment] 2016-07-18 21:56
Closed as not reproducible. Please reopen if you still have this issue.

**Closed by rtimush** 2016-07-18 21:56 UTC
Labels: bug
